[package]
name = "arinc653-wasm-harness"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
wasmtime = "36"
url = "2.5"
binrw = "0.15"
log = "0.4"
colog = "1.4"
a653rs = { version = "0.6", features = ["strum", "bindings"]}
anyhow = "1.0"
strum = { version = "0.27", features = ["derive"] }
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"]}
toml = "0.9"
